### ISSUE TITLE
🚨 CI Pipeline Failure: Outdated GitHub Action `actions/setup-rust@v1`

### ISSUE THREAD

**Issue by Jagadeeshftw** [Stellopay/stellopay-core#35]
## 📋 Issue Summary
The Soroban Rust Smart Contracts CI pipeline is failing due to an outdated GitHub Action that is no longer available.

## �� Error Details
Error: Unable to resolve action actions/setup-rust@v1, action not found

## 🎯 Problem Description
The CI pipeline is using `actions/setup-rust@v1` which has been deprecated and is no longer available. This action was replaced by `actions/setup-rust@v2` and later versions.

## 📁 Affected Files
- `.github/workflows/ci.yml` (or similar workflow file)
- Any other workflow files using `actions/setup-rust@v1`

### Option 1: Update to Latest Version (Recommended)
Replace the outdated action with the latest stable version:

```yaml
# Before (broken)
- uses: actions/setup-rust@v1

# After (fixed)
- uses: actions/setup-rust@v2
```

### Option 2: Use Specific Version
If you need a specific version for compatibility:

```yaml
- uses: actions/setup-rust@v2.0.0
```

### Option 3: Use Latest with Rust Toolchain
For Soroban development, you might want to specify the Rust toolchain:

```yaml
- uses: actions/setup-rust@v2
  with:
    toolchain: stable
    target: wasm32-unknown-unknown
    components: rust-src
```

## 📝 Acceptance Criteria
- [ ] Update `actions/setup-rust@v1` to `actions/setup-rust@v2`
- [ ] Verify CI pipeline passes successfully
- [ ] Test that Soroban contract builds still work
- [ ] Update any documentation referencing the old action version

## 🔗 References
- [actions/setup-rust GitHub repository](https://github.com/actions/setup-rust)
- [GitHub Actions deprecation policy](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith)
- [Soroban Rust toolchain requirements](https://soroban.stellar.org/docs/getting-started/setup)

## 💡 Additional Recommendations
1. **Set up dependabot alerts** for GitHub Actions to prevent future issues
2. **Pin action versions** to specific commits for better reproducibility
3. **Add workflow validation** to catch similar issues early
4. **Document the CI setup** for future maintainers

---
**Priority:** High  
**Estimated Effort:** 15 minutes  
**Impact:** Blocks all CI/CD operations
